update yml

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -3,26 +3,6 @@ on:
   push:
     branches: ["main"]
 jobs:
-  lhci:
-    environment:
-      name: Lighthouse CI
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Install Node.js
-        uses: actions/setup-node@v1
-        with:
-          node-version: 14
-      - name: npm install, build
-        run: |
-          npm install
-          npm run build
-      - name: run lighthouse-ci
-        run: |
-          npm install -g @lhci/cli@0.8.x
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
-        env:
-          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
   build:
     environment:
       name: Build
@@ -59,3 +39,15 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./build
+  lhci:
+    environment:
+      name: Lighthouse CI
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: run lighthouse-ci
+        run: |
+          npm install -g @lhci/cli@0.8.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
