update yml

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -3,21 +3,26 @@ on:
   push:
     branches: ["main"]
 jobs:
-  lhci:
+  lighthouse:
     environment:
       name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Audit URLs using Lighthouse
-        uses: treosh/lighthouse-ci-action@v9
+      - name: Install Node.js
+        uses: actions/setup-node@v1
         with:
-          urls: |
-            https://chenhuei.github.io/
-            https://chenhuei.github.io/Wordle/
-          budgetPath: ./budget.json
-          uploadArtifacts: true
-          temporaryPublicStorage: true
+          node-version: 14
+      - name: npm install, build
+        run: |
+          npm install
+          npm run build
+      - name: run lighthouse-ci
+        run: |
+          npm install -g @lhci/cli@0.8.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
   build:
     environment:
       name: Build
@@ -28,7 +33,7 @@ jobs:
         uses: actions/setup-node@v1
         with:
           node-version: 13.x
-      - name: npm install
+      - name: npm install, build
         run: |
           npm ci
           npm run build
