update yml

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -3,6 +3,26 @@ on:
   push:
     branches: ["main"]
 jobs:
+  lhci:
+    environment:
+      name: Lighthouse CI
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Install Node.js
+        uses: actions/setup-node@v1
+        with:
+          node-version: 14
+      - name: npm install, build
+        run: |
+          npm install
+          npm run build
+      - name: run lighthouse-ci
+        run: |
+          npm install -g @lhci/cli@0.8.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
   build:
     environment:
       name: Build
@@ -22,22 +42,10 @@ jobs:
         with:
           name: production-files
           path: ./build
-  lhci:
-    environment:
-      name: Lighthouse CI
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - name: run lighthouse-ci
-        run: |
-          npm install -g @lhci/cli@0.8.x
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
-        env:
-          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
   deploy:
     environment:
       name: Deploy
-    needs: lhci
+    needs: build
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main'
     steps:
