update yml

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -22,10 +22,22 @@ jobs:
         with:
           name: production-files
           path: ./build
+  lhci:
+    environment:
+      name: Lighthouse CI
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: run lighthouse-ci
+        run: |
+          npm install -g @lhci/cli@0.8.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
   deploy:
     environment:
       name: Deploy
-    needs: build
+    needs: lhci
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main'
     steps:
@@ -39,15 +51,3 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./build
-  lhci:
-    environment:
-      name: Lighthouse CI
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - name: run lighthouse-ci
-        run: |
-          npm install -g @lhci/cli@0.8.x
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
-        env:
-          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
